Fix UnboundLocalError while recovering from an error
See https://github.com/furlongm/patchman/issues/690#issuecomment-4574985291:
if you upgrade a Patchman 3 setup to Patchman 4, the migrations don't
correctly alter the hosts_host table and leave the tags column as NOT
NULL, which then causes issues processing reports for previously unseen
hosts.  Host.objects.get_or_create() raises, the exception is caught
and logged, and then subsequent `if host:` check fails with an

  UnboundLocalError: cannot access local variable 'host' where it is not associated with a value